# **Chronic Health Prediction**

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
encoding = 'latin1'

data = pd.read_csv('/content/drive/MyDrive/BRFSS Project/Reduced_Dataset.csv', encoding=encoding, error_bad_lines=False)

<ipython-input-4-7a93a06c1586>:3: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  data = pd.read_csv('/content/drive/MyDrive/BRFSS Project/Reduced_Dataset.csv', encoding=encoding, error_bad_lines=False)
<ipython-input-4-7a93a06c1586>:3: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('/content/drive/MyDrive/BRFSS Project/Reduced_Dataset.csv', encoding=encoding, error_bad_lines=False)

In [5]:
df = data.copy()

In [6]:
df

,X_state,stateres,genhlth,poorhlth,physhlth,menthlth,hlthpln1,persdoc2,medcost,sleptim1,...,avedrnk2,fruitju1,fruit1,fvbeans,fvgreen,fvorang,vegetab1,exeroft1,seatbelt,sex
0,Alabama,Yes,Fair,30.00000,30.0,29.000000,Yes,"Yes, only one",No,7.052409,...,2.000000,304.0,104.0,303.0,310.0,303.0,203.451751,135.776184,Always,Female
1,Alabama,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,6.000000,...,2.209727,305.0,301.0,310.0,203.0,202.0,203.000000,105.000000,Always,Female
2,Alabama,Yes,Good,0.00000,3.0,2.000000,Yes,"Yes, only one",No,9.000000,...,4.000000,301.0,203.0,202.0,202.0,310.0,330.000000,135.776184,Always,Female
3,Alabama,Yes,Very good,0.00000,2.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.000000,202.0,306.0,202.0,310.0,305.0,204.000000,205.000000,Always,Female
4,Alabama,Yes,Good,0.00000,10.0,2.000000,Yes,"Yes, only one",No,6.000000,...,2.000000,0.0,302.0,101.0,310.0,303.0,101.000000,135.776184,Always,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489346,Puerto Rico,Yes,Fair,0.00000,14.0,15.000000,Yes,More than one,No,6.000000,...,2.209727,101.0,302.0,101.0,101.0,202.0,101.000000,135.776184,Always,Female
489347,Puerto Rico,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,7.000000,...,2.209727,0.0,302.0,101.0,0.0,0.0,203.451751,135.776184,Always,Male
489348,Puerto Rico,Yes,Fair,0.00000,15.0,20.000000,Yes,More than one,Yes,7.000000,...,2.209727,102.0,103.0,0.0,304.0,203.0,205.000000,204.000000,Always,Female
489349,Puerto Rico,Yes,Very good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.209727,310.0,205.0,101.0,203.0,0.0,203.000000,104.000000,Always,Female
489350,Puerto Rico,Yes,Good,30.00000,30.0,3.380493,Yes,More than one,No,7.000000,...,2.209727,0.0,203.0,207.0,202.0,201.0,207.000000,103.000000,Always,Male

**Dropping rows with less common responses**

In [7]:
# Iterate through columns with datatype 'object'
for column in df.select_dtypes(include='object').columns:
    # Count the occurrences of each unique value in the column
    value_counts = df[column].value_counts()

    # Get the unique values that occur less than 20 times
    values_to_drop = value_counts[value_counts < 50].index

    # Drop the rows where the column value is in values_to_drop
    df = df[~df[column].isin(values_to_drop)]

# Reset the index after dropping rows
df = df.reset_index(drop=True)

In [8]:
df

,X_state,stateres,genhlth,poorhlth,physhlth,menthlth,hlthpln1,persdoc2,medcost,sleptim1,...,avedrnk2,fruitju1,fruit1,fvbeans,fvgreen,fvorang,vegetab1,exeroft1,seatbelt,sex
0,Alabama,Yes,Fair,30.00000,30.0,29.000000,Yes,"Yes, only one",No,7.052409,...,2.000000,304.0,104.0,303.0,310.0,303.0,203.451751,135.776184,Always,Female
1,Alabama,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,6.000000,...,2.209727,305.0,301.0,310.0,203.0,202.0,203.000000,105.000000,Always,Female
2,Alabama,Yes,Good,0.00000,3.0,2.000000,Yes,"Yes, only one",No,9.000000,...,4.000000,301.0,203.0,202.0,202.0,310.0,330.000000,135.776184,Always,Female
3,Alabama,Yes,Very good,0.00000,2.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.000000,202.0,306.0,202.0,310.0,305.0,204.000000,205.000000,Always,Female
4,Alabama,Yes,Good,0.00000,10.0,2.000000,Yes,"Yes, only one",No,6.000000,...,2.000000,0.0,302.0,101.0,310.0,303.0,101.000000,135.776184,Always,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481963,Puerto Rico,Yes,Fair,0.00000,14.0,15.000000,Yes,More than one,No,6.000000,...,2.209727,101.0,302.0,101.0,101.0,202.0,101.000000,135.776184,Always,Female
481964,Puerto Rico,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,7.000000,...,2.209727,0.0,302.0,101.0,0.0,0.0,203.451751,135.776184,Always,Male
481965,Puerto Rico,Yes,Fair,0.00000,15.0,20.000000,Yes,More than one,Yes,7.000000,...,2.209727,102.0,103.0,0.0,304.0,203.0,205.000000,204.000000,Always,Female
481966,Puerto Rico,Yes,Very good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.209727,310.0,205.0,101.0,203.0,0.0,203.000000,104.000000,Always,Female
481967,Puerto Rico,Yes,Good,30.00000,30.0,3.380493,Yes,More than one,No,7.000000,...,2.209727,0.0,203.0,207.0,202.0,201.0,207.000000,103.000000,Always,Male

**Converting columns containing numeric values to int/float**

In [9]:
# Function to check if a value is numeric
def is_numeric(value):
    try:
        float(value)
        return True
    except ValueError:
        return False

# Convert object-type columns to int or float based on numeric content in at least one row
for column in df.select_dtypes(include='object').columns:
    # Check if any row in the column has purely numeric values
    if any(df[column].apply(is_numeric)):
        # Convert to float
        df[column] = pd.to_numeric(df[column], errors='coerce')

        # Convert to int if there are no decimal values, otherwise to float
        df[column] = df[column].astype(int) if all(pd.notna(value) and value.is_integer() for value in df[column]) else df[column].astype(float)

In [10]:
# datatype of all the columns
for column in df.columns:
    print(f"{column}: {df[column].dtypes}")

X_state: object
stateres: object
genhlth: object
poorhlth: float64
physhlth: float64
menthlth: float64
hlthpln1: object
persdoc2: object
medcost: object
sleptim1: float64
bphigh4: object
bpmeds: object
toldhi2: object
cvdinfr4: object
cvdcrhd4: object
cvdstrk3: object
asthma3: object
chcocncr: object
havarth3: object
addepev2: object
chckidny: object
diabete3: object
educa: object
marital: object
employ1: object
income2: object
weight2: int64
height3: float64
renthom1: object
qlactlm2: object
useequip: object
blind: object
smoke100: object
smokday2: object
usenow3: object
alcday5: float64
avedrnk2: float64
fruitju1: float64
fruit1: float64
fvbeans: float64
fvgreen: float64
fvorang: float64
vegetab1: float64
exeroft1: float64
seatbelt: object
sex: object

In [11]:
df

,X_state,stateres,genhlth,poorhlth,physhlth,menthlth,hlthpln1,persdoc2,medcost,sleptim1,...,avedrnk2,fruitju1,fruit1,fvbeans,fvgreen,fvorang,vegetab1,exeroft1,seatbelt,sex
0,Alabama,Yes,Fair,30.00000,30.0,29.000000,Yes,"Yes, only one",No,7.052409,...,2.000000,304.0,104.0,303.0,310.0,303.0,203.451751,135.776184,Always,Female
1,Alabama,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,6.000000,...,2.209727,305.0,301.0,310.0,203.0,202.0,203.000000,105.000000,Always,Female
2,Alabama,Yes,Good,0.00000,3.0,2.000000,Yes,"Yes, only one",No,9.000000,...,4.000000,301.0,203.0,202.0,202.0,310.0,330.000000,135.776184,Always,Female
3,Alabama,Yes,Very good,0.00000,2.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.000000,202.0,306.0,202.0,310.0,305.0,204.000000,205.000000,Always,Female
4,Alabama,Yes,Good,0.00000,10.0,2.000000,Yes,"Yes, only one",No,6.000000,...,2.000000,0.0,302.0,101.0,310.0,303.0,101.000000,135.776184,Always,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481963,Puerto Rico,Yes,Fair,0.00000,14.0,15.000000,Yes,More than one,No,6.000000,...,2.209727,101.0,302.0,101.0,101.0,202.0,101.000000,135.776184,Always,Female
481964,Puerto Rico,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,7.000000,...,2.209727,0.0,302.0,101.0,0.0,0.0,203.451751,135.776184,Always,Male
481965,Puerto Rico,Yes,Fair,0.00000,15.0,20.000000,Yes,More than one,Yes,7.000000,...,2.209727,102.0,103.0,0.0,304.0,203.0,205.000000,204.000000,Always,Female
481966,Puerto Rico,Yes,Very good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.209727,310.0,205.0,101.0,203.0,0.0,203.000000,104.000000,Always,Female
481967,Puerto Rico,Yes,Good,30.00000,30.0,3.380493,Yes,More than one,No,7.000000,...,2.209727,0.0,203.0,207.0,202.0,201.0,207.000000,103.000000,Always,Male

In [12]:

df.rename(columns={
    'cvdinfr4': 'Heart Attack',
    'cvdcrhd4': 'Angina Or Coronary Heart Disease',
    'cvdstrk3': 'Stroke',
}, inplace=True)

In [13]:
df

,X_state,stateres,genhlth,poorhlth,physhlth,menthlth,hlthpln1,persdoc2,medcost,sleptim1,...,avedrnk2,fruitju1,fruit1,fvbeans,fvgreen,fvorang,vegetab1,exeroft1,seatbelt,sex
0,Alabama,Yes,Fair,30.00000,30.0,29.000000,Yes,"Yes, only one",No,7.052409,...,2.000000,304.0,104.0,303.0,310.0,303.0,203.451751,135.776184,Always,Female
1,Alabama,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,6.000000,...,2.209727,305.0,301.0,310.0,203.0,202.0,203.000000,105.000000,Always,Female
2,Alabama,Yes,Good,0.00000,3.0,2.000000,Yes,"Yes, only one",No,9.000000,...,4.000000,301.0,203.0,202.0,202.0,310.0,330.000000,135.776184,Always,Female
3,Alabama,Yes,Very good,0.00000,2.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.000000,202.0,306.0,202.0,310.0,305.0,204.000000,205.000000,Always,Female
4,Alabama,Yes,Good,0.00000,10.0,2.000000,Yes,"Yes, only one",No,6.000000,...,2.000000,0.0,302.0,101.0,310.0,303.0,101.000000,135.776184,Always,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481963,Puerto Rico,Yes,Fair,0.00000,14.0,15.000000,Yes,More than one,No,6.000000,...,2.209727,101.0,302.0,101.0,101.0,202.0,101.000000,135.776184,Always,Female
481964,Puerto Rico,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,7.000000,...,2.209727,0.0,302.0,101.0,0.0,0.0,203.451751,135.776184,Always,Male
481965,Puerto Rico,Yes,Fair,0.00000,15.0,20.000000,Yes,More than one,Yes,7.000000,...,2.209727,102.0,103.0,0.0,304.0,203.0,205.000000,204.000000,Always,Female
481966,Puerto Rico,Yes,Very good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.209727,310.0,205.0,101.0,203.0,0.0,203.000000,104.000000,Always,Female
481967,Puerto Rico,Yes,Good,30.00000,30.0,3.380493,Yes,More than one,No,7.000000,...,2.209727,0.0,203.0,207.0,202.0,201.0,207.000000,103.000000,Always,Male

In [14]:

# Display the data types of each column before conversion
print("Before Conversion:")
print(df.dtypes)

# Convert columns with 'object' data type to 'categorical'
df = df.astype({col: 'category' for col in df.select_dtypes(include='object').columns})

# Display the data types of each column after conversion
print("\nAfter Conversion:")
print(df.dtypes)

Before Conversion:
X_state                              object
stateres                             object
genhlth                              object
poorhlth                            float64
physhlth                            float64
menthlth                            float64
hlthpln1                             object
persdoc2                             object
medcost                              object
sleptim1                            float64
bphigh4                              object
bpmeds                               object
toldhi2                              object
Heart Attack                         object
Angina Or Coronary Heart Disease     object
Stroke                               object
asthma3                              object
chcocncr                             object
havarth3                             object
addepev2                             object
chckidny                             object
diabete3                             object
educa                                object
marital                              object
employ1                              object
income2                              object
weight2                               int64
height3                             float64
renthom1                             object
qlactlm2                             object
useequip                             object
blind                                object
smoke100                             object
smokday2                             object
usenow3                              object
alcday5                             float64
avedrnk2                            float64
fruitju1                            float64
fruit1                              float64
fvbeans                             float64
fvgreen                             float64
fvorang                             float64
vegetab1                            float64
exeroft1                            float64
seatbelt                             object
sex                                  object
dtype: object

After Conversion:
X_state                             category
stateres                            category
genhlth                             category
poorhlth                             float64
physhlth                             float64
menthlth                             float64
hlthpln1                            category
persdoc2                            category
medcost                             category
sleptim1                             float64
bphigh4                             category
bpmeds                              category
toldhi2                             category
Heart Attack                        category
Angina Or Coronary Heart Disease    category
Stroke                              category
asthma3                             category
chcocncr                            category
havarth3                            category
addepev2                            category
chckidny                            category
diabete3                            category
educa                               category
marital                             category
employ1                             category
income2                             category
weight2                                int64
height3                              float64
renthom1                            category
qlactlm2                            category
useequip                            category
blind                               category
smoke100                            category
smokday2                            category
usenow3                             category
alcday5                              float64
avedrnk2                             float64
fruitju1                             float64
fruit1                               float64
fvbeans                              float64
fvgreen                              float64
fvorang                              float64
vegetab1                             float64
exeroft1                             float64
seatbelt                            category
sex                                 category
dtype: object

In [20]:
df

,X_state,stateres,genhlth,poorhlth,physhlth,menthlth,hlthpln1,persdoc2,medcost,sleptim1,...,avedrnk2,fruitju1,fruit1,fvbeans,fvgreen,fvorang,vegetab1,exeroft1,seatbelt,sex
0,Alabama,Yes,Fair,30.00000,30.0,29.000000,Yes,"Yes, only one",No,7.052409,...,2.000000,304.0,104.0,303.0,310.0,303.0,203.451751,135.776184,Always,Female
1,Alabama,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,6.000000,...,2.209727,305.0,301.0,310.0,203.0,202.0,203.000000,105.000000,Always,Female
2,Alabama,Yes,Good,0.00000,3.0,2.000000,Yes,"Yes, only one",No,9.000000,...,4.000000,301.0,203.0,202.0,202.0,310.0,330.000000,135.776184,Always,Female
3,Alabama,Yes,Very good,0.00000,2.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.000000,202.0,306.0,202.0,310.0,305.0,204.000000,205.000000,Always,Female
4,Alabama,Yes,Good,0.00000,10.0,2.000000,Yes,"Yes, only one",No,6.000000,...,2.000000,0.0,302.0,101.0,310.0,303.0,101.000000,135.776184,Always,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481963,Puerto Rico,Yes,Fair,0.00000,14.0,15.000000,Yes,More than one,No,6.000000,...,2.209727,101.0,302.0,101.0,101.0,202.0,101.000000,135.776184,Always,Female
481964,Puerto Rico,Yes,Good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,7.000000,...,2.209727,0.0,302.0,101.0,0.0,0.0,203.451751,135.776184,Always,Male
481965,Puerto Rico,Yes,Fair,0.00000,15.0,20.000000,Yes,More than one,Yes,7.000000,...,2.209727,102.0,103.0,0.0,304.0,203.0,205.000000,204.000000,Always,Female
481966,Puerto Rico,Yes,Very good,5.30023,0.0,0.000000,Yes,"Yes, only one",No,8.000000,...,2.209727,310.0,205.0,101.0,203.0,0.0,203.000000,104.000000,Always,Female
481967,Puerto Rico,Yes,Good,30.00000,30.0,3.380493,Yes,More than one,No,7.000000,...,2.209727,0.0,203.0,207.0,202.0,201.0,207.000000,103.000000,Always,Male

In [21]:

# List of columns
columns_to_check = ['bphigh4', 'toldhi2', 'chcocncr', 'havarth3', 'addepev2', 'employ1', 'weight2', 'height3', 'renthom1', 'qlactlm2', 'diabete3', 'smoke100', 'asthma3', 'alcday5', 'sex']

# Check data types
data_types = df[columns_to_check].dtypes

# Display data types
print("Data Types:")
print(data_types)

# Display unique values in non-numeric columns
non_numeric_columns = df[columns_to_check].select_dtypes(exclude=['number']).columns
for column in non_numeric_columns:
    unique_values = df[column].unique()
    print(f"\nUnique values in {column}:")
    print(unique_values)

Data Types:
bphigh4     category
toldhi2     category
chcocncr    category
havarth3    category
addepev2    category
employ1     category
weight2        int64
height3      float64
renthom1    category
qlactlm2    category
diabete3    category
smoke100    category
asthma3     category
alcday5      float64
sex         category
dtype: object

Unique values in bphigh4:
['Yes', 'No', 'Told borderline or pre-hypertensive', 'Yes, but female told only during pregnancy']
Categories (4, object): ['No', 'Told borderline or pre-hypertensive', 'Yes',
                         'Yes, but female told only during pregnancy']

Unique values in toldhi2:
['Yes', 'No']
Categories (2, object): ['No', 'Yes']

Unique values in chcocncr:
['No', 'Yes']
Categories (2, object): ['No', 'Yes']

Unique values in havarth3:
['Yes', 'No']
Categories (2, object): ['No', 'Yes']

Unique values in addepev2:
['Yes', 'No']
Categories (2, object): ['No', 'Yes']

Unique values in employ1:
['Retired', 'Employed for wages', 'A homemaker', 'Out of work for less than 1 year', 'Unable to work', 'Self-employed', 'Out of work for 1 year or more', 'A student']
Categories (8, object): ['A homemaker', 'A student', 'Employed for wages',
                         'Out of work for 1 year or more', 'Out of work for less than 1 year', 'Retired',
                         'Self-employed', 'Unable to work']

Unique values in renthom1:
['Own', 'Rent', 'Other arrangement']
Categories (3, object): ['Other arrangement', 'Own', 'Rent']

Unique values in qlactlm2:
['Yes', 'No']
Categories (2, object): ['No', 'Yes']

Unique values in diabete3:
['No', 'Yes', 'No, pre-diabetes or borderline diabetes', 'Yes, but female told only during pregnancy']
Categories (4, object): ['No', 'No, pre-diabetes or borderline diabetes', 'Yes',
                         'Yes, but female told only during pregnancy']

Unique values in smoke100:
['Yes', 'No']
Categories (2, object): ['No', 'Yes']

Unique values in asthma3:
['Yes', 'No']
Categories (2, object): ['No', 'Yes']

Unique values in sex:
['Female', 'Male']
Categories (2, object): ['Female', 'Male']

In [22]:
print(df.dtypes)

X_state                             category
stateres                            category
genhlth                             category
poorhlth                             float64
physhlth                             float64
menthlth                             float64
hlthpln1                            category
persdoc2                            category
medcost                             category
sleptim1                             float64
bphigh4                             category
bpmeds                              category
toldhi2                             category
Heart Attack                        category
Angina Or Coronary Heart Disease    category
Stroke                              category
asthma3                             category
chcocncr                            category
havarth3                            category
addepev2                            category
chckidny                            category
diabete3                            category
educa                               category
marital                             category
employ1                             category
income2                             category
weight2                                int64
height3                              float64
renthom1                            category
qlactlm2                            category
useequip                            category
blind                               category
smoke100                            category
smokday2                            category
usenow3                             category
alcday5                              float64
avedrnk2                             float64
fruitju1                             float64
fruit1                               float64
fvbeans                              float64
fvgreen                              float64
fvorang                              float64
vegetab1                             float64
exeroft1                             float64
seatbelt                            category
sex                                 category
dtype: object

In [23]:
pip install -U scikit-learn joblib

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Collecting scikit-learn
  Downloading scikit_learn-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 75.3 MB/s eta 0:00:00
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (1.3.2)
Requirement already satisfied: numpy<2.0,>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.23.5)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.2.0)
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
Successfully installed scikit-learn-1.3.2

# **Multi-Label Chronic Condition Prediction Model**

In [24]:
import joblib
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
import category_encoders as ce

# Ignore convergence warnings
warnings.filterwarnings("ignore", category=UserWarning)

# Assume df is your DataFrame with relevant columns

# List of chronic conditions
chronic_conditions = ['Heart Attack', 'Angina Or Coronary Heart Disease', 'Stroke']

# Selected features
selected_features_chronic_conditions = ['bphigh4', 'toldhi2', 'chcocncr', 'havarth3', 'addepev2', 'employ1', 'weight2', 'height3', 'renthom1', 'qlactlm2', 'diabete3', 'smoke100', 'asthma3', 'alcday5', 'sex']

# Create a dictionary to store trained models
models = {}

for condition in chronic_conditions:
    # Extract selected features and target variable
    X = df[selected_features_chronic_conditions].copy()  # Make a copy to avoid modifying the original DataFrame
    y = df[condition]

    # Convert categorical columns to 'category' data type
    categorical_columns = X.select_dtypes(include='category').columns
    X[categorical_columns] = X[categorical_columns].astype('category')

    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Apply Ordinal Encoding to categorical columns
    encoder = ce.OrdinalEncoder(cols=categorical_columns)
    X_train_encoded = encoder.fit_transform(X_train, y_train)
    X_test_encoded = encoder.transform(X_test)

    # Train Random Forest model
    model = RandomForestClassifier(random_state=42)
    model.fit(X_train_encoded, y_train)

    # Save the trained model
    model_filename = f'{condition.lower().replace(" ", "_")}_model.pkl'
    joblib.dump(model, model_filename)
    models[condition] = model_filename

    # Make predictions
    y_pred = model.predict(X_test_encoded)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)
    confusion_mat = confusion_matrix(y_test, y_pred)

    print(f"Results for {condition} using selected features:")
    print(f"Accuracy: {accuracy}")
    print("Confusion Matrix:")
    print(confusion_mat)
    print("Classification Report:")
    print(classification_rep)
    print("\n")

import pickle

# Save the trained model with pickle
with open(model_filename, 'wb') as file:
    pickle.dump(model, file)

Results for Heart Attack using selected features:
Accuracy: 0.9319148494719588
Confusion Matrix:
[[89526  1157]
 [ 5406   305]]
Classification Report:
              precision    recall  f1-score   support

          No       0.94      0.99      0.96     90683
         Yes       0.21      0.05      0.09      5711

    accuracy                           0.93     96394
   macro avg       0.58      0.52      0.52     96394
weighted avg       0.90      0.93      0.91     96394



Results for Angina Or Coronary Heart Disease using selected features:
Accuracy: 0.9317073676784862
Confusion Matrix:
[[89477  1156]
 [ 5427   334]]
Classification Report:
              precision    recall  f1-score   support

          No       0.94      0.99      0.96     90633
         Yes       0.22      0.06      0.09      5761

    accuracy                           0.93     96394
   macro avg       0.58      0.52      0.53     96394
weighted avg       0.90      0.93      0.91     96394



Results for Stroke using selected features:
Accuracy: 0.9534722078137643
Confusion Matrix:
[[91811   628]
 [ 3857    98]]
Classification Report:
              precision    recall  f1-score   support

          No       0.96      0.99      0.98     92439
         Yes       0.13      0.02      0.04      3955

    accuracy                           0.95     96394
   macro avg       0.55      0.51      0.51     96394
weighted avg       0.93      0.95      0.94     96394

In [27]:
# Save the trained OrdinalEncoder
encoder_filename = 'ordinal_encoder.pkl'
joblib.dump(encoder, encoder_filename)

['ordinal_encoder.pkl']

# **Model Testing**

**Sample Input 1**

In [30]:

# Load the saved OrdinalEncoder
encoder_filename = 'ordinal_encoder.pkl'
ordinal_encoder = joblib.load(encoder_filename)

# Prepare new input data
new_data = pd.DataFrame({
    'bphigh4': ['No'],
    'toldhi2': ['No'],
    'chcocncr': ['No'],
    'havarth3': ['No'],
    'addepev2': ['No'],
    'employ1': ['Retired'],
    'weight2': [60],
    'height3': [150],
    'renthom1': ['Own'],
    'qlactlm2': ['No'],
    'diabete3': ['Yes'],
    'smoke100': ['Yes'],
    'asthma3': ['No'],
    'alcday5': [1],
    'sex': ['Male']
})

# Ensure that categorical columns are of type 'category' with the correct categories
categorical_columns = new_data.select_dtypes(include='category').columns
for col in categorical_columns:
    new_data[col] = pd.Categorical(new_data[col], categories=ordinal_encoder.mapping[col]['mapping'])

# Transform the new data using the loaded OrdinalEncoder
new_data_encoded = ordinal_encoder.transform(new_data)

# Define the list of chronic conditions and their corresponding model paths
chronic_conditions_models = [
    ('Heart Attack', '/content/heart_attack_model.pkl'),
    ('Angina Or Coronary Heart Disease', '/content/angina_or_coronary_heart_disease_model.pkl'),
    ('Stroke', '/content/stroke_model.pkl')
]

# Make predictions for each class
predictions = {}

for condition, model_filename in chronic_conditions_models:
    # Load the trained model
    loaded_model = joblib.load(model_filename)

    # Get the probability of the positive class (Yes)
    probability_yes = loaded_model.predict_proba(new_data_encoded)[:, 1][0]

    # Store the result
    predictions[condition] = probability_yes * 100

# Display the predictions for each chronic health condition
for condition, probability in predictions.items():
    print(f"There is {probability:.2f}% chance for {condition}")

There is 12.00% chance for Heart Attack
There is 10.00% chance for Angina Or Coronary Heart Disease
There is 10.00% chance for Stroke

**Sample Input 2**

In [31]:

# Load the saved OrdinalEncoder
encoder_filename = 'ordinal_encoder.pkl'
ordinal_encoder = joblib.load(encoder_filename)

# Prepare new input data
new_data = pd.DataFrame({
    'bphigh4': ['Yes'],
    'toldhi2': ['No'],
    'chcocncr': ['No'],
    'havarth3': ['No'],
    'addepev2': ['No'],
    'employ1': ['Retired'],
    'weight2': [60],
    'height3': [150],
    'renthom1': ['Own'],
    'qlactlm2': ['No'],
    'diabete3': ['Yes'],
    'smoke100': ['Yes'],
    'asthma3': ['Yes'],
    'alcday5': [4],
    'sex': ['Male']
})

# Ensure that categorical columns are of type 'category' with the correct categories
categorical_columns = new_data.select_dtypes(include='category').columns
for col in categorical_columns:
    new_data[col] = pd.Categorical(new_data[col], categories=ordinal_encoder.mapping[col]['mapping'])

# Transform the new data using the loaded OrdinalEncoder
new_data_encoded = ordinal_encoder.transform(new_data)

# Define the list of chronic conditions and their corresponding model paths
chronic_conditions_models = [
    ('Heart Attack', '/content/heart_attack_model.pkl'),
    ('Angina Or Coronary Heart Disease', '/content/angina_or_coronary_heart_disease_model.pkl'),
    ('Stroke', '/content/stroke_model.pkl')
]

# Make predictions for each class
predictions = {}

for condition, model_filename in chronic_conditions_models:
    # Load the trained model
    loaded_model = joblib.load(model_filename)

    # Get the probability of the positive class (Yes)
    probability_yes = loaded_model.predict_proba(new_data_encoded)[:, 1][0]

    # Store the result
    predictions[condition] = probability_yes * 100

# Display the predictions for each chronic health condition
for condition, probability in predictions.items():
    print(f"There is {probability:.2f}% chance for {condition}")

There is 31.00% chance for Heart Attack
There is 23.00% chance for Angina Or Coronary Heart Disease
There is 14.00% chance for Stroke